set -g default-shell $SHELL
set -a terminal-features "xterm-256color:RGB"
set -sg escape-time 10
set -wg pane-base-index 1
set -g base-index 1
set -g focus-events on
set -g automatic-rename on
set -g renumber-windows on
set -g status-position top 
set -g mode-keys vi
set -g popup-border-lines "rounded"
set -g mouse

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf

bind H run "~/.config/scripts/tmux-sessionizer.sh ~"
bind p display-popup -h14 -s "bg=terminal" -E "~/.config/scripts/tmux-sessionizer.sh" 
bind g display-popup -h3 -w21 -E "~/.config/scripts/open-github.sh; sleep 1; tmux popup -C"

bind -n M-k resize-pane -U 5
bind -n M-j resize-pane -D 5
bind -n M-h resize-pane -L 5
bind -n M-l resize-pane -R 5

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "christoomey/vim-tmux-navigator"

source-file ~/.config/tmux/mutagen.conf

set -g status-left "" 
set -g status-right "#S" 
set -g window-status-separator ""

set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_text_color "terminal"
set -g @catppuccin_window_number_color "#{@outline}"
set -g @catppuccin_window_current_text_color "terminal"
set -g @catppuccin_window_current_number_color "#{?client_prefix,#{@primary_container},#{@primary}},bold" 

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
run ~/.config/tmux/plugins/tpm/tpm

