format = """
$username\
$directory\
$git_branch\
$git_status
$time\
$character
"""

[character]
vimcmd_symbol = "[❮](bold #4d9eaa)"
vimcmd_visual_symbol = "[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold #f6c177)"
vimcmd_replace_one_symbol = "[❮](bold #f6c177)"

[username]
format = "[$user : ]($style)"
disabled = false
show_always = true

[directory]
truncation_symbol = "../"
read_only = " -w"

[time]
style = "bold #98c379"
disabled = false 
format = "[$time ]($style)"
time_format = "%I:%M"

[git_branch]
format = 'on [$branch]($style) '

[git_status]
format = '([$conflicted$diverged$untracked$stashed$modified$staged$ahead_behind]($style))'
ahead = "+${count}"
behind = "-${count}"

