set -g default-shell $SHELL
set -a terminal-features "xterm-256color:RGB"
set -sg escape-time 1
set -wg pane-base-index 1
set -g base-index 1
set -g focus-events on
set -g automatic-rename on
set -g automatic-rename-format "#{b:pane_current_path}:#{pane_current_command}"
set -g status-interval 1 
set -g renumber-windows on
set -g status-position top 
set -g mode-keys vi
set -g status-keys emacs
set -g popup-border-lines "rounded"
set -g mouse

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf

bind H run "~/.config/scripts/tmux-sessionizer.sh ~"
bind p display-popup -h14 -s "bg=terminal" -E "~/.config/scripts/tmux-sessionizer.sh" 
bind g display-popup -h3 -w21 -E "~/.config/scripts/open-github.sh; sleep 1; tmux popup -C"
bind Q killw
bind q killw -a

bind -n M-up resize-pane -U 5
bind -n M-down resize-pane -D 5
bind -n M-left resize-pane -L 5
bind -n M-right resize-pane -R 5

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "christoomey/vim-tmux-navigator"

source-file ~/.config/tmux/matugen.conf
run ~/.config/tmux/plugins/tpm/tpm

