set -g status-left "" 
set -g status-right "#S" 
set -g status-style fg={{colors.inverse_primary.default.hex}},bg=terminal
set -g window-status-format "#W#{?client_prefix,#I, }"
set -g window-status-style fg={{colors.inverse_primary.default.hex}}
set -g window-status-current-format "#W "
set -g window-status-separator "#[fg={{colors.surface_container_highest.default.hex}}]• "
set -g window-status-current-style "#{?client_prefix,fg={{colors.secondary.default.hex}} bold,fg={{colors.primary_fixed_dim.default.hex}}}"
