[main]
include=~/.config/foot/themes/noctalia
include = ~/.config/foot/theme.ini
font = CaskaydiaCove Nerd Font Mono:size=12
pad = 8x10 center-when-maximized-and-fullscreen

[scrollback]
lines = 10000

[mouse]
hide-when-typing = yes

[colors-dark]
alpha = 0.85

[key-bindings]
prompt-prev=Control+Shift+k
prompt-next=Control+Shift+j

# vim: ft=dosini
