[main]
include = ~/.config/foot/theme.ini
font = JetBrainsMonoNL Nerd Font:size=12
pad = 8x8 center-when-maximized-and-fullscreen

[scrollback]
lines = 10000

[mouse]
hide-when-typing = yes

[colors]
alpha = 0.85

[key-bindings]
prompt-prev=Control+Shift+k
prompt-next=Control+Shift+j

# vim: ft=dosini
